package te

const (
	EscRIS   = "c"
	EscIND   = "D"
	EscNEL   = "E"
	EscHTS   = "H"
	EscRI    = "M"
	EscDECSC = "7"
	EscDECRC = "8"

	EscDECALN = "8"

	EscICH     = "@"
	EscCUU     = "A"
	EscCUD     = "B"
	EscCUF     = "C"
	EscCUB     = "D"
	EscCNL     = "E"
	EscCPL     = "F"
	EscCHA     = "G"
	EscCUP     = "H"
	EscED      = "J"
	EscEL      = "K"
	EscIL      = "L"
	EscDL      = "M"
	EscDCH     = "P"
	EscECH     = "X"
	EscHPR     = "a"
	EscDA      = "c"
	EscVPA     = "d"
	EscVPR     = "e"
	EscHVP     = "f"
	EscTBC     = "g"
	EscSM      = "h"
	EscRM      = "l"
	EscSGR     = "m"
	EscDSR     = "n"
	EscDECSTBM = "r"
	EscHPA     = "'"
)
